---
# Installs Composer package manager as a global utility

- name: download composer
  get_url: url=https://getcomposer.org/installer dest=/home/controller/composer.phar mode=644
- name: install composer
  command: "php /home/controller/composer.phar"

- name: ensure directory exists for system wide installation
  file: path=/usr/local/bin owner=root group=root state=directory
- name: make composer available system wide
  command: "mv /home/controller/composer.phar /usr/local/bin/composer"
