---
# Installs Composer package manager as a global utility

- name: determine if composer installed
  stat: path=/usr/local/bin/composer
  register: composer_fact_composer_installed

- include: install-composer.yml
  when: composer_fact_composer_installed.stat.exists == false

- include: controller-user.yml
  when: composer_fact_composer_installed.stat.exists == false

- include: app-user.yml
  when: composer_fact_composer_installed.stat.exists == false
